---
- name: Make sure dnf-plugins.core installed
  become: yes
  shell: |
    dnf install -y dnf-plugins-core
  args:
    executable: /bin/bash

- name: Install docker repository
  become: yes
  shell: |
    # Try direct download instead of config-manager
    curl -fsSL https://download.docker.com/linux/fedora/docker-ce.repo -o /etc/yum.repos.d/docker-ce.repo
  args:
    executable: /bin/bash

- name: Install docker
  become: yes
  shell: |
    dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin
  args:
    executable: /bin/bash

- name: Start Docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user dubadub to docker group
  become: yes
  user:
    name: dubadub
    groups: docker
    append: yes
