---
- name: Install Nginx
  become: yes
  shell: |
    dnf install -y nginx
  args:
    executable: /bin/bash

- name: Start and enable Nginx service
  become: yes
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Configure SELinux for nginx network access
  become: yes
  shell: |
    setsebool -P httpd_can_network_connect 1
  args:
    executable: /bin/bash

- name: Upload nginx config
  become: true
  copy:
    src: nginx.conf
    dest: "/etc/nginx/nginx.conf"
  notify:
    - Restart nginx

- name: Validate nginx config
  become: true
  shell: nginx -t
  args:
    executable: /bin/bash

- name: Add user nginx to wwwdata group
  become: yes
  user:
    name: nginx
    groups: wwwdata
    append: yes

- name: Ensure firewalld is running
  become: yes
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Configure firewall rules
  become: yes
  shell: |
    firewall-cmd --permanent --add-service=http
    firewall-cmd --permanent --add-service=https
    firewall-cmd --reload
  args:
    executable: /bin/bash
