---
- name: Restart nginx
  become: true
  systemd:
    name: nginx
    state: restarted

- name: Reload paleo.io
  shell: |
    systemctl --user daemon-reload
    systemctl --user enable {{ service_name }}.service
    systemctl --user start {{ service_name }}.service

- name: Restart paleo.io

  shell: |
    cd {{ deployment_root }} && docker-compose pull
    systemctl --user restart {{ service_name }}.service
